// get todo request

export const GET_DOCTERS_REQUEST = "GET_DOCTER_REQUEST";
export const GET_DOCTERS_SUCCESS = "GET_DOCTER_SUCCESS";
export const GET_DOCTERS_FAILURE = "GET_DOCTER_FAILURE";

//  POST REQUEST
export const POST_DOCTER_REQUEST = "POST_DOCTER_REQUEST";
export const POST_DOCTER_SUCCESS = "POST_DOCTER_SUCCESS";
export const POST_DOCTER_FAILURE = "POST_DOCTER_FAILURE";